### ISSUE TITLE
Pipeline overview lag/incorrect display

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#369]
https://jam.dev/c/06563356-e272-4b98-becc-7b80c15e968d

**Comment by fatchat** [comment]
@Ishankoradia loading indicator?

**Comment by Ishankoradia** [comment]
@fatchat will add a loading indicator. I am guessing not for tonight's release right ?

**Comment by Ishankoradia** [comment]
added loading indicator here #375 . actually it was already there but placed outside the async function.

**Comment by nairabhishek73** [comment]
Doesn't seem to be working. I tried again for STIR on staging.

**Comment by fatchat** [comment]
oh i just released it, try now

**Comment by nairabhishek73** [comment]
I still see a lag: https://jam.dev/c/323c89e7-3ca8-42b8-8767-9a57cb41be51

**Comment by fatchat** [comment]
the loading indicator got disabled (bypassed) when polling was introduced, will fix via PR #393
